name: neverlandv1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.13.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.7

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/z.png
    - assets/neverland.png
    - assets/intro_logo.png
    - assets/people1.png
    - assets/people2.png
    - assets/people3.png
    - assets/people4.png
    - assets/Moon.png
    - assets/Sun.png
    - assets/morning.png
    - assets/night.png
    - assets/push.png
    - assets/user1.png
    - assets/user2.png
    - assets/user3.png
    - assets/user4.png


