// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDifb4gjTdBYDa4jphNb7gbuwALr5e0Gv4',
    appId: '1:1080735080948:web:78e071ca25abbd43e699a1',
    messagingSenderId: '1080735080948',
    projectId: 'neverland-349ba',
    authDomain: 'neverland-349ba.firebaseapp.com',
    storageBucket: 'neverland-349ba.firebasestorage.app',
    measurementId: 'G-V5J21659TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByyhVrbR2_-RwNER5yfsYw77qfT0kW_Hc',
    appId: '1:1080735080948:android:7bb19df03dc39032e699a1',
    messagingSenderId: '1080735080948',
    projectId: 'neverland-349ba',
    storageBucket: 'neverland-349ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd8k7hpuyw5GUDAVvxCv3aqQ4avfnztb0',
    appId: '1:1080735080948:ios:35d29effcfb4778ae699a1',
    messagingSenderId: '1080735080948',
    projectId: 'neverland-349ba',
    storageBucket: 'neverland-349ba.firebasestorage.app',
    iosBundleId: 'com.example.neverlandv1',
  );
}
