// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAUb8IvBSLLl1OU5GgIWtfO_rDTyjaQms',
    appId: '1:691253356942:web:629d061c98d30f1cde5cdf',
    messagingSenderId: '691253356942',
    projectId: 'neverland-v1-second',
    authDomain: 'neverland-v1-second.firebaseapp.com',
    storageBucket: 'neverland-v1-second.firebasestorage.app',
    measurementId: 'G-BJEP16FDCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8d-47X40o1D4M8Wld3LZ374FKhNDqCMU',
    appId: '1:691253356942:android:dffecf22fa407964de5cdf',
    messagingSenderId: '691253356942',
    projectId: 'neverland-v1-second',
    storageBucket: 'neverland-v1-second.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCog1zKB5LNM4ohZMbK2IQ42D_8XywfPTo',
    appId: '1:691253356942:ios:15c00d5324c6d7d4de5cdf',
    messagingSenderId: '691253356942',
    projectId: 'neverland-v1-second',
    storageBucket: 'neverland-v1-second.firebasestorage.app',
    iosBundleId: 'com.example.neverlandv1',
  );

}